language: cpp

compiler:
 - gcc
 - clang

before_install:
 - sudo apt-add-repository -y ppa:beineri/opt-qt521
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get -qq update

install:
 - sudo apt-get -qq install g++-4.8 gcc-4.8
 - sudo apt-get -qq install qt52base

before_script:
 - export CXX="g++-4.8" CC="gcc-4.8"
 - source /opt/qt52/bin/qt52-env.sh

script:
 - qmake "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" "DEFINES+=CI"
 - make
