language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo apt-get install qt5-default
  - python3 deploy/download.py

script:
  - qmake "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" "DEFINES+=CI"
  - make
