install:
  - set QTDIR=C:\Qt\5.6\msvc2015
  - set PATH=%PATH%;%QTDIR%\bin
  - C:\Python37\python deploy\download.py

build_script:
  - qmake "DEFINES+=CI"
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - nmake
