install:
  - set QTDIR=C:\Qt\5.6\msvc2015
  - set PATH=%PATH%;%QTDIR%\bin

build_script:
  - qmake "DEFINES+=CI"
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - nmake

artifacts:
  - path: bin\win32
    name: application

deploy:
  - provider: GitHub
    tag: neutral
    release: Neutral Build
    auth_token:
      secure: t8/7KFOH0H0vl+tpP21AFg8T0cKG0bt2FfOg8EUK/EI+KJbfZXhpMwCfwW1/qIhW
    artifact: application
    draft: true
    prerelease: true
    force_update: true
